
-- tb_aerodromo
CREATE TABLE TB_AERODROMO
(
	ID_AERODROMO		SMALLINT IDENTITY,
	SG_AERODROMO		CHAR(4)			    NOT NULL,
	NM_AERODROMO		VARCHAR(100)		NOT NULL,
	NM_CIDADE			VARCHAR(50),
	SG_UF				CHAR(2),
	NM_PAIS				VARCHAR(50)			NOT NULL,
	NM_CONTINENTE		VARCHAR(16)			NOT NULL,
	
	CONSTRAINT PK_TB_AERODROMO		PRIMARY KEY (ID_AERODROMO),
	CONSTRAINT UQ_SG_AERODROMO		UNIQUE (SG_AERODROMO),
	CONSTRAINT UQ_NM_AERODROMO		UNIQUE (NM_AERODROMO),
	CONSTRAINT CH_TB_AERODROMO_NM_CONTINENTE	CHECK(NM_CONTINENTE = 'AMERICA DO SUL' OR NM_CONTINENTE ='OCEANIA' OR NM_CONTINENTE = 'AMERICA DO NORTE'
        OR NM_CONTINENTE = 'AMERICA CENTRAL' OR NM_CONTINENTE = 'AFRICA' OR NM_CONTINENTE = 'EUROPA' OR NM_CONTINENTE = 'ASIA'),
)


-- tb_empresa
CREATE TABLE TB_EMPRESA
(
    ID_EMPRESA            TINYINT IDENTITY,
    SG_EMPRESA            CHAR(3) NOT NULL,
    NM_EMPRESA            VARCHAR(100) NOT NULL,
    DS_TIPO_EMPRESA       VARCHAR(50),	

    CONSTRAINT PK_ID_EMPRESA    PRIMARY KEY(ID_EMPRESA),
	CONSTRAINT CH_DS_TIPO_EMPRESA	CHECK (DS_TIPO_EMPRESA = 'BRASILEIRA' OR DS_TIPO_EMPRESA = 'ESTRANGEIRA' OR DS_TIPO_EMPRESA = 'NÃO INFORMADO'),
)


-- tb_justificativa
CREATE TABLE TB_JUSTIFICATIVA
(
	ID_JUSTIFICATIVA TINYINT IDENTITY,
	SG_JUSTIFICATIVA CHAR(2) NOT NULL,
	DS_JUSTIFICATIVA VARCHAR(300) NOT NULL,

	CONSTRAINT PK_TB_JUSTIFICATIVA  PRIMARY KEY(ID_JUSTIFICATIVA),
	CONSTRAINT UQ_SG_JUSTIFICATIVA	UNIQUE (SG_JUSTIFICATIVA),
	CONSTRAINT CH_TB_JUSTIFCATIVA	CHECK(ID_JUSTIFICATIVA <= 100)
)


-- tb_tipo_linha
CREATE TABLE TB_TIPO_LINHA
(
	ID_TIPO_LINHA				TINYINT IDENTITY,   -- PRIMARY KEY
	CD_TIPO_LINHA				CHAR(1)	NOT NULL,	-- UNIQUE
	DS_SERVICO_TIPO_LINHA		VARCHAR(9) NOT NULL,  
	DS_NATUREZA_TIPO_LINHA		VARCHAR(13) NOT NULL,  

	CONSTRAINT PK_TB_TIPO_LINHA				PRIMARY KEY (ID_TIPO_LINHA),
	CONSTRAINT UQ_CD_TIPO_LINHA				UNIQUE (CD_TIPO_LINHA),
	CONSTRAINT CK_DS_SERVICO_TIPO_LINHA		CHECK (DS_SERVICO_TIPO_LINHA = 'MISTA' OR DS_SERVICO_TIPO_LINHA = 'CARGUEIRA'),
	CONSTRAINT CK_DS_NATUREZA_TIPO_LINHA	CHECK (DS_NATUREZA_TIPO_LINHA = 'DOMÉSTICA' OR DS_NATUREZA_TIPO_LINHA = 'INTERNACIONAL')
)


-- tb_tipo_voo
CREATE TABLE TB_TIPO_VOO
(
	ID_TIPO_VOO					TINYINT IDENTITY,
	DS_TIPO_VOO				VARCHAR(20)	NOT NULL,
	DS_CLASSIFICACAO_VOO	VARCHAR(12)	NOT NULL,

	CONSTRAINT PK_ID_TIPO_VOO	PRIMARY KEY(ID_TIPO_VOO),
	CONSTRAINT CH_DS_TIPO_VOO	
		CHECK (DS_TIPO_VOO = 'REGULAR' OR DS_TIPO_VOO = 'EXTRA' OR DS_TIPO_VOO = 'RETORNO' OR DS_TIPO_VOO = 'INCLUSÃO DE ETAPA' OR DS_TIPO_VOO = 'NÃO REMUNERADO' OR DS_TIPO_VOO = 'FRETAMENTO' OR DS_TIPO_VOO = 'CHARTER'),
	CONSTRAINT UN_DS_TIPO_VOO	UNIQUE(DS_TIPO_VOO),
	CONSTRAINT CH_DS_CLASSIFICACAO_VOO 
        CHECK(DS_CLASSIFICACAO_VOO = 'REGULAR' OR DS_CLASSIFICACAO_VOO = 'NAO REGULAR' OR DS_CLASSIFICACAO_VOO = 'IMPRODUTIVO')
)


-- tb_voo
CREATE TABLE TB_VOO
(
    ID_VOO                            INT IDENTITY,
    ID_EMPRESA                        TINYINT NOT NULL,
    NR_VOO                            SMALLINT NOT NULL,
    ID_TIPO_VOO                       TINYINT NOT NULL,
    ID_TIPO_LINHA                     TINYINT NOT NULL,
    ID_AERODROMO_ORIGEM			      SMALLINT NOT NULL,
	ID_AERODROMO_DESTINO			  SMALLINT NOT NULL,
    DT_HR_PARTIDA_PREVISTA            DATETIMEOFFSET(0) NOT NULL,
    DT_HR_PARTIDA_REAL                DATETIMEOFFSET(0),
    DT_HR_CHEGADA_PREVISTA            DATETIMEOFFSET(0) NOT NULL,
    DT_HR_CHEGADA_REAL                DATETIMEOFFSET(0),
    FL_SITUACAO                       BIT NOT NULL,
    ID_JUSTIFICATIVA                  TINYINT,




    CONSTRAINT PK_TB_VOO    PRIMARY KEY (ID_VOO),

    CONSTRAINT FK_TB_VOO_TB_EMPRESA
        FOREIGN KEY (ID_EMPRESA)  REFERENCES TB_EMPRESA      (ID_EMPRESA),

    CONSTRAINT FK_TB_VOO_TB_TIPO_VOO
        FOREIGN KEY (ID_TIPO_VOO) REFERENCES TB_TIPO_VOO     (ID_TIPO_VOO),

    CONSTRAINT FK_TB_VOO_TB_TIPO_LINHA
        FOREIGN KEY (ID_TIPO_LINHA) REFERENCES TB_TIPO_LINHA   (ID_TIPO_LINHA),

    CONSTRAINT FK_TB_VOO_TB_AERODROMO_ORIGEM
        FOREIGN KEY (ID_AERODROMO_ORIGEM) REFERENCES TB_AERODROMO  (ID_AERODROMO),

	 CONSTRAINT FK_TB_VOO_TB_AERODROMO_DESTINO
        FOREIGN KEY (ID_AERODROMO_DESTINO) REFERENCES TB_AERODROMO  (ID_AERODROMO),

    CONSTRAINT CH_DT_HR_CHEGADA_REAL 
		CHECK (DT_HR_CHEGADA_REAL > DT_HR_PARTIDA_REAL),

	CONSTRAINT CH_DT_HR_CHEGADA_PREVISTA 
		CHECK (DT_HR_CHEGADA_PREVISTA > DT_HR_PARTIDA_PREVISTA),

    CONSTRAINT CH_FL_SITUACAO
        CHECK(FL_SITUACAO = 1 OR FL_SITUACAO = 0),  

    CONSTRAINT FK_TB_VOO_TB_JUSTIFICATIVA
        FOREIGN KEY (ID_JUSTIFICATIVA)    REFERENCES TB_JUSTIFICATIVA   (ID_JUSTIFICATIVA),
)



